// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKZjPIuCejFbag2jluO9RiLfPoGbnDEY',
    appId: '1:963322788122:android:621da3ec6798d7459254a3',
    messagingSenderId: '963322788122',
    projectId: 'lets-chat-a5d43',
    storageBucket: 'lets-chat-a5d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfEGCestF2y4ML-KVSA_KnqChxAsula4',
    appId: '1:963322788122:ios:82e18bf95dad92139254a3',
    messagingSenderId: '963322788122',
    projectId: 'lets-chat-a5d43',
    storageBucket: 'lets-chat-a5d43.appspot.com',
    androidClientId: '963322788122-b74lpdpl40tpsf21bde6imk4601msgln.apps.googleusercontent.com',
    iosClientId: '963322788122-rtrom44tg7ic1scoqe0pkrc02llr5pqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );

}